# Change these first
owner: malang-dev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

# User agent is mandatory. if not set response will be 403.
# Reference: https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#user-agent
user-agent: bramanda48

sites:
  - name: Malang.dev
    url: https://malang.dev
  - name: New Jersey - hosteroid.uk
    url: $SITES_SERVER_NJ
  - name: Jakarta - hostdata.id
    url: $SITES_SERVER_ID
  - name: Malang - cloudflare
    url: $SITES_SERVER_ML
  - name: Passbolt
    url: $SITES_PASSBOLT_URL/healthcheck/status.json
    headers:
      - "Content-Type: application/json"
  - name: Roundcube
    url: $SITES_ROUNDCUBE_URL
  - name: Blog Wordpress
    url: https://blog.malang.dev

assignees: # Users to assign downtime issues (optional)
  - bramanda48
  
status-website:
  cname: status.malang.dev
  name: ""
  favicon: https://status.malang.dev/favicon.png
  logoUrl: https://status.malang.dev/wordmark-white.svg
  theme: light
  themeUrl: https://status.malang.dev/custom.css
  introTitle: "**Malang.dev** uptime monitor and status page. powered entirely by GitHub."
  introMessage: "See the status and check for outages on the malang.dev service and more."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
